name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - run: pip install black flake8
      - run: make lint
